### ISSUE TITLE
subprocess.CalledProcessError: 

### ISSUE THREAD

**Issue by diegomd90** [AvilPage/kraken-db-builder#2]
Hello Avil;

I'm having some issues while running:

`kdb --db-type standard --threads 24 --cache-dir --no-check-certificate`

And I got

`Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/bioinformatica/.local/lib/python3.10/site-packages/kdb.py", line 71, in download_taxanomy
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz | xargs -n 1 -P 4 wget -c' returned non-zero exit status 123.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bioinformatica/.local/bin/kdb", line 8, in <module>
    sys.exit(main())
  File "/home/bioinformatica/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/bioinformatica/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/bioinformatica/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bioinformatica/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/bioinformatica/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/bioinformatica/.local/lib/python3.10/site-packages/kdb.py", line 147, in main
    future1.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
subprocess.CalledProcessError: Command 'echo https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz | xargs -n 1 -P 4 wget -c' returned non-zero exit status 123.`

**Comment by ChillarAnand** [comment]
@diegomd90 Did you run this command in your machine and check?

```
echo ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz | xargs -n 1 -P 4 wget -c
```

I am not seeing any issues with this step on this machine.
